version: '3'

services:
  nginx:
    image: nginx:alpine3.22
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./realestate.conf:/etc/nginx/nginx.conf
      - /var/www/html:/usr/share/nginx/html
      - /etc/letsencrypt/live/real-estate-app.pro/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/real-estate-app.pro/privkey.pem:/etc/nginx/ssl/privkey.pem

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: real_estate_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d real_estate_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/real_estate_db
      GOOGLE_API_KEY: AIzaSyDwN8UV2bfiMz9afTicKRh6ynHgMGK3YwU
      VIRTUAL_HOST: real-estate-app.pro
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    environment:
      VIRTUAL_HOST: real-estate-app.pro
      VIRTUAL_PATH: /
    depends_on:
      - backend

volumes:
  db_data: