version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: real_estate_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Опционально: пробрасываем порт БД на хост для удобства отладки

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app # Монтируем директорию с кодом для горячей перезагрузки
    ports:
      - "8000:8000" # Пробрасываем порт FastAPI на хост
    depends_on:
      - db # Указываем, что бэкенд зависит от БД
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/real_estate_db # Переменная для подключения к БД

  frontend: # ДОБАВЬ ЭТОТ БЛОК!
    build: ./frontend # Указывает Docker'у, где искать Dockerfile для фронтенда
    ports:
      - "80:80" # Пробрасываем порт Nginx на хост (стандартный HTTP порт)
    depends_on:
      - backend # Фронтенд зависит от бэкенда

volumes:
  db_data: # Объявляем именованный том для сохранения данных БД