services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: real_estate_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d real_estate_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/real_estate_db
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    env_file:
      - .env
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
